#
# @file Makefile.simple
# @author Akagi201
# @date 2014/06/03
#
# Makefile.simple
#

objects = main.o kbd.o comand.o display.o \
		  insert.o search.o files.o utils.o

edit: $(objects)
	cc -o edit $(objects)

$(objects): defs.h
kbd.o command.o files.o: command.h
display.o insert.o search.o files.o: buffer.h

.PHONY: clean

clean:
	rm edit $(objects)
